#!/usr/bin/env sh

yabai -m config                                 \
    menubar_opacity              1.0            \
    skip_window_focus_animation  on             \
    layout                       float          \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize

echo "yabai configuration loaded.."
