[layout]
column-gap = 20
window-gap = 20
outer-gap = 20
outer-gap-top = 8
resize-detent = true
height-presets = [0.5, 0.666]
width-presets = [0.5, 0.666]

[focus]
system-events = "on-screen"
# follows-mouse = true

[mouse]
hide = true
follows-focus = "except-hover"
trackpad-scroll = "magnet"
trackpad-scroll-direction = "natural"

[animation]
transition = "smooth"
window = "crop"
cover = "immediate"

[keys]
fn-1 = "focus-workspace 1"
fn-2 = "focus-workspace 2"
fn-3 = "focus-workspace 3"
fn-4 = "focus-workspace 4"
fn-5 = "focus-workspace 5"
fn-q = "focus-workspace q"
fn-w = "focus-workspace w"
fn-e = "focus-workspace e"
fn-r = "focus-workspace r"
fn-t = "focus-workspace t"

fn-shift-1 = "move-to-workspace-and-focus 1"
fn-shift-2 = "move-to-workspace-and-focus 2"
fn-shift-3 = "move-to-workspace-and-focus 3"
fn-shift-4 = "move-to-workspace-and-focus 4"
fn-shift-5 = "move-to-workspace-and-focus 5"
fn-shift-q = "move-to-workspace-and-focus q"
fn-shift-w = "move-to-workspace-and-focus w"
fn-shift-e = "move-to-workspace-and-focus e"
fn-shift-r = "move-to-workspace-and-focus r"
fn-shift-t = "move-to-workspace-and-focus t"

fn-h = "focus left"
fn-j = "focus down"
fn-k = "focus up"
fn-l = "focus right"
fn-f = "fullscreen"
fn-shift-f = "float toggle"

fn-shift-h = "move-window left"
fn-shift-j = "move-window down"
fn-shift-k = "move-window up"
fn-shift-l = "move-window right"

fn-shift-leftbracket = "consume-or-expel left"
fn-shift-rightbracket = "consume-or-expel right"
fn-equal = "grow 10%"
fn-minus = "shrink 10%"

fn-space = "exec osascript -e 'tell application \"Ghostty\" to new window'"

[guide.names]
enabled = true
gap = 120

[[window-rules]]
smaller-than-focused = 0.6
from-focused-app = true
float = true
