[layout]
column-gap = 20
window-gap = 20
outer-gap = 20
outer-gap-top = 8
resize-detent = true
height-presets = [0.5, 0.666]
width-presets = [0.5, 0.666]

[focus]
system-events = "on-screen"
# follows-mouse = true

[mouse]
hide = true
follows-focus = "except-hover"
trackpad-scroll = "magnet"
trackpad-scroll-direction = "natural"

[animation]
transition = "smooth"
window = "crop"
cover = "immediate"

[keys]
fn-q = "focus-workspace 1"
fn-w = "focus-workspace 2"
fn-e = "focus-workspace 3"
fn-a = "focus-workspace 4"
fn-s = "focus-workspace 5"
fn-d = "focus-workspace 6"

fn-shift-q = "move-to-workspace-and-focus 1"
fn-shift-w = "move-to-workspace-and-focus 2"
fn-shift-e = "move-to-workspace-and-focus 3"
fn-shift-a = "move-to-workspace-and-focus 4"
fn-shift-s = "move-to-workspace-and-focus 5"
fn-shift-d = "move-to-workspace-and-focus 6"

fn-h = "focus left"
fn-j = "focus down"
fn-k = "focus up"
fn-l = "focus right"
fn-f = "fullscreen"
fn-shift-f = "float toggle"

fn-shift-h = "move-window left"
fn-shift-j = "move-window down"
fn-shift-k = "move-window up"
fn-shift-l = "move-window right"

fn-shift-leftbracket = "consume-or-expel left"
fn-shift-rightbracket = "consume-or-expel right"
fn-equal = "grow 10%"
fn-minus = "shrink 10%"

fn-space = "exec osascript -e 'tell application \"Ghostty\" to new window'"

[guide.names]
enabled = true
gap = 120

[[window-rules]]
smaller-than-focused = 0.6
from-focused-app = true
float = true
