unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -s extended-keys on
set -as terminal-features 'xterm-ghostty:extkeys'
set -g mouse on
set -g base-index 1
set -g renumber-windows on

bind C-t new-window
bind -r C-h previous-window
bind -r C-l next-window

bind -r C-S-h swap-window -d -t -1
bind -r C-S-l swap-window -d -t +1
bind -r C-S-H swap-window -d -t -1
bind -r C-S-L swap-window -d -t +1

set -g status-position top
set -g status-style bg=default,fg=colour7
set -g window-status-separator ' '
set -g window-status-format '#[fg=colour7,bg=colour8] #W '
set -g window-status-current-format '#[fg=colour0,bg=colour2,bold] #W '
set -g status-left '#{?client_prefix,#[fg=colour7#,bg=colour4],#[fg=colour0#,bg=colour3]} tmux #[default] '
set -g status-left-length 30
set -g status-right ''
